chore(deps): add `sax` dependency from `xml-js`
Release was failing when `xml-js` was added as a bundled package due to
this error:

```
(node:26218) [MODULE_NOT_FOUND] Error Plugin: @ibm-skills-network/olx-cli: Cannot find module 'sax'
```

This is because `sax` is bundled in the xml-js package.json but not in
the olx-cli package.json.